export default [
  {title: '1', src: "assets/images/gallery/1.jpg"},
  {title: '2', src: "assets/images/gallery/2.jpg"},
  {title: '3', src: "assets/images/gallery/3.jpg"},
  {title: '4', src: "assets/images/gallery/4.jpg"},
  {title: '5', src: "assets/images/gallery/5.jpg"},
  {title: '6', src: "assets/images/gallery/6.jpg"},
  {title: '7', src: "assets/images/gallery/7.jpg"},
  {title: '8', src: "assets/images/gallery/8.jpg"},
  {title: '9', src: "assets/images/gallery/9.jpg"},
  {title: '10', src: "assets/images/gallery/10.jpg"},
  {title: '11', src: "assets/images/gallery/11.jpg"},
  {title: '12', src: "assets/images/gallery/12.jpg"},
  {title: '13', src: "assets/images/gallery/13.jpg"},
  {title: '14', src: "assets/images/gallery/14.jpg"},
  {title: '15', src: "assets/images/gallery/15.jpg"},
  {title: '16', src: "assets/images/gallery/16.jpg"},
  {title: '17', src: "assets/images/gallery/17.jpg"},
  {title: '18', src: "assets/images/gallery/18.jpg"},
  {title: '19', src: "assets/images/gallery/19.jpg"},
  {title: '20', src: "assets/images/gallery/20.jpg"},
  {title: '21', src: "assets/images/gallery/21.jpg"},
  {title: '22', src: "assets/images/gallery/22.jpg"},
  {title: '23', src: "assets/images/gallery/23.jpg"},
  {title: '24', src: "assets/images/gallery/24.jpg"},
  {title: '25', src: "assets/images/gallery/25.jpg"},
  {title: '26', src: "assets/images/gallery/26.jpg"},

];